### ISSUE TITLE
Improve extracting information from the Tuxepedia

### ISSUE THREAD

**Issue by AndyMender** [Tuxemon/Tuxemon#458]
Currently, there is a script called `sync-wiki-monsters.py`, which as far as I could tell scrapes the Tuxepedia for Tuxemon data. I would like to improve the script and perhaps refactor it into a Python module so that the module can later be included in the main game files and the Tuxemon information used in-game (in the _Tuxedex_?), for instance from a JSON file or from a SQLite database.

I haven't worked on this project before, but I do have extensive programming experience so I would like to give a helping hand :).

**EDIT:** This is potentially related to https://github.com/Tuxemon/Tuxemon/issues/347 and might address some issues there.

**EDIT2:** After some considerations I decided it would be most convenient to use SQLite as the backend for the local copy of the Tuxepedia (highly recommended for other parts of the project as well! :)) and provide a convenient API to pull information from it into the game.

**Comment by bitcraft** [comment]
I'm not sure that we are ready for a new database API.  I do like SQLite, but tuxemon targets Android, so you would have to be sure that whatever you are proposing would work there.  If you find improvements for converting to JSON, those are certainly welcome.  Anything more than that would require some planning to get right, but willing to consider it.  Before any database changes are implemented, I'd like to see #347 closed, as well as cleanup with all the related "database" classes.

**Comment by AndyMender** [comment]
I'll try to have a look at #347, too. I'm honestly not hellbent on using SQLite, though I do believe it would work on Android just as well. Regardless of the presumed backend, a unified API might be more important here.

Thanks for the feedback :).

**Comment by bitcraft** [comment]
There are a couple things to consider, but overall, I do support a SQL based backend.
* Many of our contributors are not programmers, so JSON was a compromise between allowing programmers and non-programmers to edit the game.  Using SQLite would need an interface to edit the game that anyone can use.
* It should be generic enough to not compromise our ability to save games.  Currently, the JSON entities are serialized to disk, so whatever API/backened is used needs to support serializing the objects to disk and loading them back.

**Comment by AndyMender** [comment]
> - Many of our contributors are not programmers, so JSON was a compromise between allowing programmers and non-programmers to edit the game. Using SQLite would need an interface to edit the game that anyone can use.

In a personal project of mine I used JSON to define item and monster data, precisely because those were easier to edit and more transparent. In a group project I contributed to we used YAML with a very well defined structure for that purpose. An SQLite backend would of course require a clean and readable API not only for the rest of the game, but also for users more adept at coding.

> - It should be generic enough to not compromise our ability to save games. Currently, the JSON entities are serialized to disk, so whatever API/backened is used needs to support serializing the objects to disk and loading them back.

The project I mentioned (Unknown Horizons) used SQLite database files as savegame files. In fact, compressed SQLite files are a common approach even in bigger projects :). Compression aside, though, SQLite databases can be easily viewed in the venerable[ SQLite Browser](http://sqlitebrowser.org/).

**Comment by bitcraft** [comment]
> In a personal project of mine I used JSON to define item and monster data, precisely because those were easier to edit and more transparent. In a group project I contributed to we used YAML with a very well defined structure for that purpose. An SQLite backend would of course require a clean and readable API not only for the rest of the game, but also for users more adept at coding.

I do really like YAML.  It think might be a better fit than JSON because I have seen people struggle a bit with annoying syntax errors.  I have experimented with migrating the JSON to YAML, and it was fine, but i don't want to drop the external file structure the game uses.  There are people in the project who edit text files (JSON) with notepad and run the game to see changes, so I want to preserve that aspect of the game....ability to extend and modify without specialized knowledge or tools.

I think we agree on this aspect, so thats great.

> The project I mentioned (Unknown Horizons) used SQLite database files as savegame files. In fact, compressed SQLite files are a common approach even in bigger projects :). Compression aside, though, SQLite databases can be easily viewed in the venerable SQLite Browser. Such a switch of course is a bigger effort, requires a broad interface for saving/loading and is kind of out of the scope of this issue :).

I agree, better reserved for another feature, but worth looking into.

**Comment by AndyMender** [comment]
> I do really like YAML. It think might be a better fit than JSON because I have seen people struggle a bit with annoying syntax errors. I have experimented with migrating the JSON to YAML, and it was fine, but i don't want to drop the external file structure the game uses. There are people in the project who edit text files (JSON) with notepad and run the game to see changes, so I want to preserve that aspect of the game....ability to extend and modify without specialized knowledge or tools.

Alright, then it's clear to me :). For now I'm working on a modular extractor library to cleanly scrape the Tuxepedia HTML and output it into a JSON file + store the sprites in an organised fashion. The API module would then load the entire JSON into memory and provide lookup to particular elements (Tuxemon data, sprites, anims, etc.) via methods. However, it might be worth splitting the Tuxemon data into separate JSON files so that not everything is loaded into memory at once. Relevant to Android devices, which don't have loads of memory to spare.

What do you think? :)

**Comment by xirsoi** [comment]
I'm not sure the solution to difficult syntax issues is to switch to a format that has significant whitespace.

**Comment by bitcraft** [comment]
The project is written in python, which also has significant whitespace.  Have you used YAML for an appreciable amount of time?  Its hard to ignore the benefits of YAML compared to JSON, especially for non developers.

**Comment by bitcraft** [comment]
> Alright, then it's clear to me :). For now I'm working on a modular extractor library to cleanly scrape the Tuxepedia HTML and output it into a JSON file + store the sprites in an organised fashion. The API module would then load the entire JSON into memory and provide lookup to particular elements (Tuxemon data, sprites, anims, etc.) via methods.

It already works this way.  I can't recall any shortcomings at the moment; it does work pretty good.  Any improvements are welcome of course.

**Comment by AndyMender** [comment]
I made some progress with optimizing the Tuxepedia extractor and for now the complete JSON response looks like this:
```python
{ 'Securipaw': {'blurp': 'Ruthless, merciless and silent, this tuxemon can hunt '
                        'out intruders with its advanced built-in technology. '
                        'They will often dig their sharp, saber teeth into '
                        'their opponents, often hospitalising them.',
               'call': None,
               'sprites': {'back': None,
                           'front': None,
                           'menu1': None,
                           'menu2': None},
               'types': ['Metal'],
               'url': 'https://wiki.tuxemon.org/index.php?title=Securipaw'},
 'Selket': {'blurp': '',
            'call': None,
            'sprites': {'back': 'Selket_back.png',
                        'front': 'Selket_front.png',
                        'menu1': None,
                        'menu2': None},
            'types': ['Untyped'],
            'url': 'https://wiki.tuxemon.org/index.php?title=Selket'}}
```
The code is available as a class, but I would like to add download steps to the sprites and the call sound files. This then overlaps with #347. As you can see, I only store the base file name in the JSON, since the paths can be dynamically built in the Python code, however the URLs are fully resolvable, for instance :).

**Comment by bitcraft** [comment]
@xirsoi I was going to copy/pase the JSON from the message above, but it uses single quotes and connot be parse.  Thats just one case of why JSON is difficult to use for people.  YAML is much easier for small to medium length documents.  The whitespace is 2 spaces and with a monospace font, not difficult to understand.

```YAML
---
slug: txmn_cairfrey
name_trans: txmn_cairfrey_name
description_trans: txmn_cairfrey_descr
category_trans: txmn_cairfrey_category
attack_base: 60
defense_base: 7
hp_base: 50
special_attack_base: 6
special_defense_base: 10
speed_base: 7
attack_mod: 1
defense_mod: 1
hp_mod: 1
special_attack_mod: 1
special_defense_mod: 1
speed_mod: 1
exp_give_mod: 3
exp_req_mod: 27
ai: RandomAI
moveset:
- level_learned: 2
  technique: technique_pound
- level_learned: 2
  technique: technique_bite
sprites:
  battle1: gfx/sprites/battle/cairfrey-front.png
  battle2: gfx/sprites/battle/cairfrey-back.png
  menu1: gfx/sprites/battle/cairfrey-menu01.png
  menu2: gfx/sprites/battle/cairfrey-menu02.png
types:
- earth
weight: 25
```
```YAML
---
slug: item_potion
name_trans: item_potion_name
description_trans: item_potion_descr
execute_trans: combat_used_x
success_trans: generic_thing_success
failure_trans: generic_thing_failure
effects:
- heal
power: 50
sort: potion
sprite: gfx/items/potion.png
target:
  enemy monster: 1
  enemy team: 0
  enemy trainer: 0
  own monster: 2
  own team: 0
  own trainer: 0
  item: 0
type: Consumable
usable_in:
- MainCombatMenuState
- WorldState
```

I'm not making a movement to use it for Tuxemon, but I feel the need to defend significant whitespace because sometimes it is a sensitive topic for some people.
